apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: kavinduorg/frontend:fcde38ade6
