apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: kavinduorg/admin:tag
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
