apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-ss
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # It tells Kubernetes to make all mounted volumes writable by group ID 999.
      securityContext:
        fsGroup: 999
      # for the c scripts to run /data/db should be empty. So we can use an init container to clear the data in the volume before the main container starts.
      # initContainers:
      #   - name: clear-mongo-data
      #     image: busybox:1.36
      #     command:
      #       - sh
      #       - -c
      #       - rm -rf /data/db/*
      #     volumeMounts:
      #       - name: mongodb-pvc
      #         mountPath: /data/db
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:8.0-ubuntu2204
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: db-user-secret
            - secretRef:
                name: db-root-secret
          volumeMounts:
            - name: mongodb-pvc
              mountPath: /data/db
            # this script only works if /data/db is emty. elso we are using the job
            # but after adding the user for the first time, it will save in the /data/db and the script will not be needed.
            - name: db-init-config
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: db-init-config
          configMap:
            name: db-init-config
  volumeClaimTemplates:
    - metadata:
        name: mongodb-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp3"
        resources:
          requests:
            storage: 1Gi
