apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          image: kavinduorg/stage-frontend:a9fac8eb34
